### ISSUE TITLE
Need summary tables for combo-plots and numeric-vs-numeric plots

### ISSUE THREAD

**Issue by bokov** [UTHSCSA-CIRD/GPC-Weight-Health-Survey#10]
In the [Alex_fpTables](https://github.com/UTHSCSA-CIRD/GPC-Weight-Health-Survey/tree/Alex_fpTables) branch, there are summary tables for all the cases, not just discrete vs discrete graphs.

I want to eventually fold these into a release.

**Comment by Milanara** [comment]
I really should have looked at the description of this task before just going ahead and adding an lm summary, lol. I'll go scout that branch and move the summary tables over.

**Comment by Milanara** [comment]
Didn't work again. Hmmm. I'll eventually figure out how to close a ticket through a commit.

**Comment by bokov** [comment]
Oh lol, so you're the one who added the `lm` summary? I thought I did. Anyway, I implemented and tested a universal summary just like I wanted to, so this ticket can stay closed. 

An `lm` summary is a good idea in principle, but users won't know how to interpret it nor whether`lm` is appropriate in a given context. Addressing interpretability and validity is what took most of the work with prelimA.
