### ISSUE TITLE
We really do need to be able to flip X and Y choices after all.

### ISSUE THREAD

**Issue by bokov** [UTHSCSA-CIRD/GPC-Weight-Health-Survey#11]
Turns out users often do change their mind about what looks better on the X vs the Y axis in the graph tab. Since the lists of variables are long, it's a hassle to have to scroll through them each time. It would be nice to just have a button that causes the switch to happen in one step.

**Comment by Milanara** [comment]
Fixed the issue with numerics in the X and factors in the Y while fixing this. The system now hot swaps the factor into the X and the numeric into the Y. This will simplify the code and prevent issues when adding this feature (if they have x = numeric y = factor we secretly fix this and then use coord_flip, coord_flip does not stack so adding a feature that flips the coordinates would not operate on this unless we add additional code for this special case.(ie, removing the coord_flip))
Code is: 

```
          tmp = input$yVal
          updateSelectInput(session, "yVal", selected = input$xVal)
          updateSelectInput(session, "xVal", selected = tmp)
```

**Comment by Milanara** [comment]
Flip Coordinate Plains check added. Will be pushed shortly.
