### ISSUE TITLE
Better defaults on combo plots with "Points" option

### ISSUE THREAD

**Issue by bokov** [UTHSCSA-CIRD/GPC-Weight-Health-Survey#17]
The default settings for combo plots in "Points" mode are tiny points which are always right on top of each other and so look like thin lines.

This is always going to be the case, since these points will all share a very limited set of either X or Y values. Therefore, they should be jittered from the start.

Jitter should _not_ however be the default in true scatter-plots of numeric vs numeric.

**Comment by Milanara** [comment]
Looks like mentioning them in a commit doesn't close them, fixed in latest commit: e924ab8
