### ISSUE TITLE
Need to separate controls for jitter width and point-size

### ISSUE THREAD

**Issue by bokov** [UTHSCSA-CIRD/GPC-Weight-Health-Survey#18]
...otherwise, it's confusing: you slide around the size slider until you get the points to what looks like the right size, then you click the jitter checkbox, and the points all snap to some other, no-longer-changeable size and now this slider controls something completely different than it did before.

**Comment by Milanara** [comment]
Fixed, they are now separate. For some reason when I was testing this size wasn't passing to geom_point from geom_jitter
