### ISSUE TITLE
Larger fonts on plots

### ISSUE THREAD

**Issue by bokov** [UTHSCSA-CIRD/GPC-Weight-Health-Survey#3]
We need to make the fonts larger on all the plots. Like 2X or 3X larger than the current default. Hard to see, especially on a high resolution screen.

**Comment by bokov** [comment]
And when the fonts are made larger, the x-axis labels should also be made diagonal so the long ones don't write over each other.

**Comment by Milanara** [comment]
This goes with a future design plan of mine for allowing them to add titles, labels, tilt axis etc to the graph. It will require a lot of work and an additional tab or something to store the options so that they don't get in the user's way. Going to work on 2 other issues before I work on it.

**Comment by Milanara** [comment]
Added theme options for text size, rotation, and vertical justifications.
