### ISSUE TITLE
Reverse order of color legend in bar-chart

### ISSUE THREAD

**Issue by bokov** [UTHSCSA-CIRD/GPC-Weight-Health-Survey#6]
Colors appear in the bar-chart (discrete vs discrete plots) in the reverse order of how they appear in the accompanying legend and that's confusing to user. I'm sure ggplot2 has some way of fixing that.

**Comment by Milanara** [comment]
That one was tricky: 
bp + guides(fill = guide_legend(reverse=TRUE))
bp + scale_fill_discrete(guide = guide_legend(reverse=TRUE))
from http://www.cookbook-r.com/Graphs/Legends_(ggplot2)/ 
It might be a little confusing with  site vs site and similar plots, but easier to read the others. Will push to Lauras_Alex_ShinyBranch once I get a few more issues fixed.
