### ISSUE TITLE
Document what the red vs white circles on constellation plot mean

### ISSUE THREAD

**Issue by bokov** [UTHSCSA-CIRD/GPC-Weight-Health-Survey#8]
Somewhere in the accompanying explanatory text. And what they mean is: white filled circles are on the surface of the sphere that is away from the observer and the red ones are currently facing the observer.

**Comment by Milanara** [comment]
That was an easy one. Fixed, will push to Lauras_Alex_ShinyBranch once I've gotten a few more fixes in.
